import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Activity, ArrowLeft, CheckCircle2, ListRestart, Logs, MessageSquareWarning, Shield, Users, XCircle } from "lucide-react";
import { api } from "../api";
import { getSocket } from "../socket";
import { useAuth } from "../context/AuthContext";

const TABS = [
  ["overview", "Overview", Activity], ["dlq", "DLQ", ListRestart], ["reviews", "Failed Reviews", MessageSquareWarning],
  ["evaluations", "Human Evaluation", CheckCircle2], ["corrections", "Corrections", Shield], ["logs", "Logs", Logs], ["users", "Users", Users],
];
const emptyEval = { correctness: 3, helpfulness: 3, completeness: 3, safety: 3, groundedness: 3, verdict: "needs_correction", failure_category: "model_review", severity: "medium", notes: "", expected_behavior: "", corrected_prompt: "" };

export default function DeveloperPanel() {
  const { setDevPanelOpen, user } = useAuth();
  const [tab, setTab] = useState("overview"); const [data, setData] = useState({}); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const eventRevisions = useRef({});
  const [selected, setSelected] = useState(null); const [evaluation, setEvaluation] = useState(emptyEval); const [userForm, setUserForm] = useState({ username: "", display_name: "", password: "", role: "user" });
  const load = useCallback(async () => {
    setLoading(true); setError("");
    try {
      const [overview, dlq, reviews, evaluations, corrections, logs, users] = await Promise.all([api.devOverview(), api.devDlq(), api.devReviews(), api.devEvaluations(), api.devCorrections(), api.devLogs(), api.authUsers()]);
      setData({ overview, dlq: dlq.dlq || [], reviews: reviews.reviews || [], evaluations: evaluations.evaluations || [], corrections: corrections.corrections || [], logs: logs.logs || [], users: users.users || [] });
    } catch (err) { setError(err.message); } finally { setLoading(false); }
  }, []);
  useEffect(() => { load(); const socket = getSocket(); let timer; const handlers = {}; for (const event of ["dlq:changed", "review:changed", "evaluations:changed", "corrections:changed", "audit:changed"]) { handlers[event] = (payload = {}) => { const revision = Number(payload.revision || 0); if (revision && revision <= Number(eventRevisions.current[event] || 0)) return; if (revision) eventRevisions.current[event] = revision; clearTimeout(timer); timer = setTimeout(load, 75); }; socket.on(event, handlers[event]); } return () => { clearTimeout(timer); for (const [event, handler] of Object.entries(handlers)) socket.off(event, handler); }; }, [load]);
  const source = useMemo(() => selected || data.reviews?.[0] || data.dlq?.[0], [selected, data]);
  const submitEvaluation = async (event) => { event.preventDefault(); try { await api.devCreateEvaluation({ source_type: source?.proposal_id ? "failed_review" : "manual", source_id: source?.id, prompt: source?.prompt || "", scores: Object.fromEntries(["correctness", "helpfulness", "completeness", "safety", "groundedness"].map((key) => [key, Number(evaluation[key])])), verdict: evaluation.verdict, failure_category: evaluation.failure_category, severity: evaluation.severity, notes: evaluation.notes, expected_behavior: evaluation.expected_behavior, corrected_prompt: evaluation.corrected_prompt || null }); setEvaluation(emptyEval); await load(); } catch (err) { setError(err.message); } };
  const correctDlq = async (item) => { const corrected_prompt = window.prompt("Corrected prompt", item.prompt || ""); if (!corrected_prompt) return; const expected_behavior = window.prompt("Expected behavior"); if (!expected_behavior) return; const notes = window.prompt("Correction notes"); if (!notes) return; await api.devCorrectDlq(item.id, { corrected_prompt, expected_behavior, notes, root_cause: item.root_cause || "model_or_prompt", severity: "medium", tags: ["dlq"] }); await load(); };
  const correctReview = async (item) => { const corrected_prompt = window.prompt("Corrected prompt", item.prompt || ""); if (!corrected_prompt) return; const expected_behavior = window.prompt("Expected behavior"); if (!expected_behavior) return; const notes = window.prompt("Correction notes"); if (!notes) return; await api.devCorrectReview(item.id, { corrected_prompt, expected_behavior, notes, root_cause: "review_failure", severity: "medium", tags: ["failed-review"] }); await load(); };
  const createUser = async (event) => { event.preventDefault(); try { await api.authCreateUser(userForm); setUserForm({ username: "", display_name: "", password: "", role: "user" }); await load(); } catch (err) { setError(err.message); } };
  const exportEvaluations = async () => { try { const payload = await api.devExportEvaluations(); const url = URL.createObjectURL(new Blob([`${JSON.stringify(payload, null, 2)}\n`], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = "bob-human-evaluations.json"; link.click(); URL.revokeObjectURL(url); } catch (err) { setError(err.message); } };
  const resetPassword = async (item) => { const password = window.prompt(`New password for @${item.username} (12+ characters)`); if (!password) return; try { await api.authUpdateUser(item.id, { password }); await load(); } catch (err) { setError(err.message); } };
  return (
    <main className="dev-shell">
      <header className="dev-header"><button onClick={() => setDevPanelOpen(false)}><ArrowLeft size={16} /> Back to IDE</button><div><small>ADMIN OPERATIONS</small><h1>Bob Developer Panel</h1></div><span className="dev-admin-chip">{user.display_name} · Admin</span></header>
      <div className="dev-layout"><nav className="dev-nav">{TABS.map(([id, label, Icon]) => <button key={id} className={tab === id ? "active" : ""} onClick={() => setTab(id)}><Icon size={16} /> {label}{id === "dlq" && data.overview?.open_dlq ? <b>{data.overview.open_dlq}</b> : null}</button>)}</nav>
        <section className="dev-content">{error && <div className="dev-error">{error}</div>}{loading ? <div className="dev-empty">Loading secured operations data…</div> : <>
          {tab === "overview" && <div><h2>Operations overview</h2><div className="dev-metrics"><Metric label="Open DLQ" value={data.overview?.open_dlq} /><Metric label="Failed reviews" value={data.overview?.failed_reviews} /><Metric label="Pending evaluations" value={data.overview?.pending_evaluations} /><Metric label="Error rate" value={`${((data.overview?.error_rate || 0) * 100).toFixed(1)}%`} /><Metric label="Retry rate" value={`${((data.overview?.retry_rate || 0) * 100).toFixed(1)}%`} /><Metric label="Average latency" value={`${data.overview?.average_latency_ms || 0} ms`} /><Metric label="Input tokens" value={data.overview?.input_tokens} /><Metric label="Estimated cost" value={`$${Number(data.overview?.estimated_cost_usd || 0).toFixed(4)}`} /></div><h3>Model-quality workflow</h3><p>Exhausted model calls enter the DLQ. Reviewer failures remain visible here even when users force-stage their own changes. Admin corrections create evaluation cases and never modify user files.</p></div>}
          {tab === "dlq" && <RecordList title="Dead-letter queue" items={data.dlq} empty="No exhausted model requests." selected={selected} onSelect={setSelected} renderActions={(item) => <><button onClick={() => api.devClaimDlq(item.id, "model_or_prompt").then(load)}>Claim</button><button onClick={() => correctDlq(item)}>Correct to evaluation</button><button className="danger" onClick={() => { const reason = window.prompt("Dismissal reason"); if (reason) api.devDismissDlq(item.id, reason).then(load); }}>Dismiss</button></>} />}
          {tab === "reviews" && <RecordList title="Bob reviewer failures" items={data.reviews} empty="No failed reviews." selected={selected} onSelect={setSelected} renderActions={(item) => <><button onClick={() => { setSelected(item); setTab("evaluations"); }}>Evaluate failure</button><button onClick={() => correctReview(item)}>Correct to evaluation</button></>} />}
          {tab === "evaluations" && <div><h2>Human evaluation</h2><button onClick={exportEvaluations}>Export completed cases</button><div className="dev-eval-grid"><RecordList title="Select source" items={[...(data.reviews || []), ...(data.dlq || [])]} empty="No review or DLQ records." selected={source} onSelect={setSelected} /><form className="dev-form" onSubmit={submitEvaluation}><h3>{source ? `Evaluate ${source.id}` : "Select a record"}</h3>{["correctness", "helpfulness", "completeness", "safety", "groundedness"].map((key) => <label key={key}>{key}<input type="number" min="1" max="5" value={evaluation[key]} onChange={(e) => setEvaluation((v) => ({ ...v, [key]: e.target.value }))} /></label>)}<label>Verdict<select value={evaluation.verdict} onChange={(e) => setEvaluation((v) => ({ ...v, verdict: e.target.value }))}><option>acceptable</option><option>needs_correction</option><option>invalid_failure</option></select></label><label>Expected behavior<textarea required value={evaluation.expected_behavior} onChange={(e) => setEvaluation((v) => ({ ...v, expected_behavior: e.target.value }))} /></label><label>Reviewer notes<textarea required value={evaluation.notes} onChange={(e) => setEvaluation((v) => ({ ...v, notes: e.target.value }))} /></label><label>Corrected prompt<textarea value={evaluation.corrected_prompt} onChange={(e) => setEvaluation((v) => ({ ...v, corrected_prompt: e.target.value }))} /></label><button disabled={!source}>Save evaluation revision</button></form></div><h3>Saved evaluations</h3><RecordList items={data.evaluations} empty="No saved evaluations." /></div>}
          {tab === "corrections" && <RecordList title="Prompt corrections" items={data.corrections} empty="No prompt corrections yet." />}
          {tab === "logs" && <div><h2>Redacted operational logs</h2><div className="dev-log-list">{data.logs?.map((item, index) => <pre key={`${item.timestamp}-${index}`}>{JSON.stringify(item, null, 2)}</pre>)}</div></div>}
          {tab === "users" && <div><h2>User management</h2><form className="dev-user-form" onSubmit={createUser}><input placeholder="Display name" required minLength={2} value={userForm.display_name} onChange={(e) => setUserForm((v) => ({ ...v, display_name: e.target.value }))} /><input placeholder="Username" required minLength={3} value={userForm.username} onChange={(e) => setUserForm((v) => ({ ...v, username: e.target.value }))} /><input placeholder="Temporary password (12+ chars)" type="password" required minLength={12} value={userForm.password} onChange={(e) => setUserForm((v) => ({ ...v, password: e.target.value }))} /><select value={userForm.role} onChange={(e) => setUserForm((v) => ({ ...v, role: e.target.value }))}><option value="user">User</option><option value="admin">Admin</option></select><button>Create user</button></form><div className="dev-user-list">{data.users?.map((item) => <div key={item.id}><span className="profile-avatar">{item.display_name.slice(0, 2).toUpperCase()}</span><div><strong>{item.display_name}</strong><small>@{item.username} · {item.active_sessions || 0} active session(s)</small></div><select value={item.role} onChange={(event) => api.authUpdateUser(item.id, { role: event.target.value }).then(load)}><option value="user">User</option><option value="admin">Admin</option></select><button onClick={() => resetPassword(item)}>Reset password</button><button onClick={() => api.authUpdateUser(item.id, { enabled: !item.enabled }).then(load)}>{item.enabled ? <XCircle size={14} /> : <CheckCircle2 size={14} />}{item.enabled ? "Disable" : "Enable"}</button></div>)}</div></div>}
        </>}</section></div>
    </main>
  );
}

function Metric({ label, value = 0 }) { return <div className="dev-metric"><small>{label}</small><strong>{value || 0}</strong></div>; }
function RecordList({ title, items = [], empty, selected, onSelect = () => {}, renderActions }) { return <div className="dev-records">{title && <h2>{title}</h2>}{!items.length && <div className="dev-empty">{empty}</div>}{items.map((item) => <article key={item.id} className={selected?.id === item.id ? "selected" : ""} onClick={() => onSelect(item)}><div><strong>{item.id}</strong><span className={`dev-status status-${item.status}`}>{item.status}</span></div><p>{item.error?.message || item.review || item.expected_behavior || item.prompt || "Operational record"}</p><small>{item.workspace_id || item.source_type || "system"} · {item.created_at}</small>{renderActions && <footer onClick={(e) => e.stopPropagation()}>{renderActions(item)}</footer>}</article>)}</div>; }
